### ISSUE TITLE
How to access ROS2 interface from computer on the network

### ISSUE THREAD

**Issue by ParmaJonEman** [esimkowitz/sphero-rvr-ros2#16]
I am trying to access my RVR through Matlab, with their ROS2 integration. I have the sphero-rvr-ros2 container running on my pi, and I'm able to control the robot from the flask interface, but I can't figure out how to access the ROS2 interface.

In Matlab, you are supposed to be able to do:
`    ros2("node","list","DomainID",<networkId>) `
and it should show all the nodes. I wrote a loop to do that for all IDs, 0-100, and I still can't see my robot. I've also enabled Multicast on my router.

Do you have any advice?

**Comment by esimkowitz** [comment]
Hey, yeah I didn't get to that stage when I was working on this, I already had the mechanism for the control app so I just reused that. If I had to guess, it's probably an issue with the Docker container not exposing whichever ports the ROS2 middleware requires to do its multicasting.

**Comment by esimkowitz** [comment]
Closing as complete with #17
